# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=255)),
                ('mood', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cycle_length', models.PositiveIntegerField(default=28)),
                ('average_period_length', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
