# Generated by Django 6.1

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('glasses', models.PositiveIntegerField(default=0)),
                ('goal', models.PositiveIntegerField(default=8)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
