# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Shirley', max_length=100)),
                ('theme', models.CharField(choices=[('pink', 'Blossom Pink'), ('lavender', 'Lavender Dream'), ('peach', 'Peach Sorbet'), ('mint', 'Mint Bloom')], default='pink', max_length=20)),
                ('default_water_goal', models.PositiveIntegerField(default=8)),
                ('notifications_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
